[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "20.11.1", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20.11.1", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
